<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StandFast.Application\StandFast.Application.csproj" />
    <ProjectReference Include="..\StandFast.Domain\StandFast.Domain.csproj" />
  </ItemGroup>

</Project>
